apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata: 
  name: "messages-pvc"
  labels: 
    app: "messages-db"
spec:
  storageClassName: db-storage-class
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi