apiVersion: v1
kind: ConfigMap
metadata:
  name: ssl-crt-configmap
data:
  nginx-selfsigned.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDnTCCAoWgAwIBAgIUWWGqk+XSiUNf3AqFbWHfBMju5vwwDQYJKoZIhvcNAQEL
    BQAwXjELMAkGA1UEBhMCTVgxEDAOBgNVBAgMB1l1Y2F0YW4xDzANBgNVBAcMBk1l
    cmlkYTELMAkGA1UECgwCaWcxHzAdBgkqhkiG9w0BCQEWEGVhbGprakBnbWFpbC5j
    b20wHhcNMjIxMjA4MTgyNTEzWhcNMjMxMjA4MTgyNTEzWjBeMQswCQYDVQQGEwJN
    WDEQMA4GA1UECAwHWXVjYXRhbjEPMA0GA1UEBwwGTWVyaWRhMQswCQYDVQQKDAJp
    ZzEfMB0GCSqGSIb3DQEJARYQZWFsamtqQGdtYWlsLmNvbTCCASIwDQYJKoZIhvcN
    AQEBBQADggEPADCCAQoCggEBAMAfTfqk4wTkwmtN6AQLPPwVjRgcweo+fcD6h5I6
    eWPzRvHs/CxQae1NwbX8W9v1Ts8Fs+GbyNRRtLpb/kdTsL1l4oh8K19460kSMYoA
    V8I9nyhNtIQK0vlJst+JuyWTqF+sGRLu8MWd/tj8oAwZc2EsKzRLetLXK9H8p4mh
    xaqYG+hR9WMGHGa8zVGW7Td0AZMYwFkHXwhCoqh9QOFkw6yJcLdyb0b8H3LPM5P0
    UggbxrtdbKiNvLvXpKUzapNIVlB0ay/n/wXO1d3KVo7b87AlQfbiE51Ch5BTXcn5
    ECRNGpz+DZKCcdES3xDxQI7Xow061CtzNHp+a47LCJsk0GMCAwEAAaNTMFEwHQYD
    VR0OBBYEFJef/nLqa2KMTh0t/VUqCIJ558txMB8GA1UdIwQYMBaAFJef/nLqa2KM
    Th0t/VUqCIJ558txMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
    AEKLag+Z+/efzt4wQTNYXbXJ+cjruWVjcRRhpNZw6iKh2vPR9w0cO5fiNWCygc3h
    fxN1BPG+znaHygz0TL6dpElOGDAgMugj2TmwqiDGP8hSyHXlylgv0uWW+tnIGoA3
    opMk01G26U0AwQO1PGyVUvq4C73hLGuzpOZETZueRP5wxjYfqZe2eFzM+MAuGuxp
    6izy/Zxq9haWuMFdPK9QujVmfh2y6WcgzeQ7qhMtFSQ2Iy+4+TRGvDnQwy6bSbnG
    st7E1OUg+eKMR9jP7zZKZ2VyoGtGC35/FVF8gg6tFYMJhn9DB/Pfl2wmVzYeHFv3
    M+qKtTZ8Z0znTsNZt796Go8=
    -----END CERTIFICATE-----