apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-interface-deployment
  labels:
    app: user-interface
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: user-interface
  template:
    metadata:
      labels:
        app: user-interface
    spec:
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-configmap 
        - name: ssl-crt-volume
          configMap:
            name: ssl-crt-configmap
        - name: ssl-key-volume
          secret:
            secretName: ssl-key-secret

      containers:
      - name: user-interface
        image: ealjkj/user-interface
        volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d
          - name: ssl-crt-volume
            mountPath: /etc/ssl/certs
          - name: ssl-key-volume
            mountPath: /etc/ssl/private
        ports:
        - containerPort: 443
        # command: ["tail", "-f", "/dev/null"]
  
  